//! Typst renderer — in-dexter index markers and term list glossary.

use typst_syntax::{parse, SyntaxKind, SyntaxNode};

use crate::curate::terms::CuratedTermsFile;
use crate::render::{Annotation, Renderer};

/// In-dexter import line prepended to annotated files.
const IN_DEXTER_IMPORT: &str = "#import \"@preview/in-dexter:0.7.2\": *\n";

/// Typst renderer using in-dexter index markers.
pub struct TypstRenderer;

impl TypstRenderer {
    /// Format a single index marker call.
    pub fn format_marker(&self, term: &str, parent_chain: &[String], main: bool) -> String {
        let func = if main { "#index-main" } else { "#index" };
        if parent_chain.is_empty() {
            format!("{func}[{term}]")
        } else {
            let args: Vec<String> = parent_chain
                .iter()
                .map(|p| format!("\"{p}\""))
                .chain(std::iter::once(format!("\"{term}\"")))
                .collect();
            format!("{func}({})", args.join(", "))
        }
    }
}

impl Renderer for TypstRenderer {
    fn annotate(&self, source: &str, annotations: &[Annotation]) -> String {
        if annotations.is_empty() {
            return source.to_string();
        }

        let mut result = source.to_string();

        // Insert markers at descending byte offsets.
        for ann in annotations {
            let marker = self.format_marker(&ann.term, &ann.parent_chain, ann.main);
            if ann.byte_offset <= result.len() {
                result.insert_str(ann.byte_offset, &marker);
            }
        }

        // Prepend import if not already present.
        if !result.contains("in-dexter") {
            result.insert_str(0, IN_DEXTER_IMPORT);
        }

        result
    }

    fn glossary(&self, terms: &CuratedTermsFile, spacing: Option<&str>) -> String {
        use std::collections::HashMap;

        let mut output = String::from("// Generated by colophon\n\n");

        if terms.terms.is_empty() {
            return output;
        }

        // Build a lookup map: term name -> CuratedTerm
        let terms_map: HashMap<&str, &crate::curate::terms::CuratedTerm> =
            terms.terms.iter().map(|t| (t.term.as_str(), t)).collect();

        // Collect top-level terms (no parent)
        let mut top_level: Vec<&crate::curate::terms::CuratedTerm> =
            terms.terms.iter().filter(|t| t.parent.is_none()).collect();
        top_level.sort_by(|a, b| a.term.to_lowercase().cmp(&b.term.to_lowercase()));

        // Emit in code mode via #terms() for spacing control.
        let spacing_arg = spacing
            .map(|s| format!(", spacing: {s}"))
            .unwrap_or_default();
        output.push_str(&format!("#terms(tight: false{spacing_arg},\n"));

        for term in top_level {
            emit_term(term, &terms_map, 1, &mut output);
        }

        output.push_str(")\n");
        output
    }
}

/// Escape Typst-significant characters in prose text.
///
/// Prevents `@mentions` becoming references, `#func` becoming code-mode
/// entries, `<label>` becoming labels, and `$math$` becoming equations.
fn escape_typst(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for ch in text.chars() {
        match ch {
            '@' | '#' | '<' | '$' | '_' | '*' => {
                out.push('\\');
                out.push(ch);
            }
            _ => out.push(ch),
        }
    }
    out
}

/// Convert a term name to a Typst label: lowercase, non-alphanumeric → hyphens, deduplicated.
fn term_label(name: &str) -> String {
    let mut label = String::with_capacity(name.len() + 5);
    label.push_str("term-");
    let mut prev_hyphen = false;
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            label.push(ch.to_ascii_lowercase());
            prev_hyphen = false;
        } else if !prev_hyphen {
            label.push('-');
            prev_hyphen = true;
        }
    }
    // Trim trailing hyphen.
    if label.ends_with('-') {
        label.pop();
    }
    label
}

/// Format see_also entries as Typst links to glossary term labels.
fn format_see_also(see_also: &[String]) -> String {
    let links: Vec<String> = see_also
        .iter()
        .map(|name| format!("#link(<{}>)[{}]", term_label(name), escape_typst(name)))
        .collect();
    format!(" _See also: {}_", links.join(", "))
}

/// Recursively emit a term as a `terms.item()` call in Typst code mode.
fn emit_term(
    term: &crate::curate::terms::CuratedTerm,
    terms_map: &std::collections::HashMap<&str, &crate::curate::terms::CuratedTerm>,
    indent: usize,
    output: &mut String,
) {
    let prefix = "  ".repeat(indent);
    let escaped_def = escape_typst(&term.definition);
    let label = term_label(&term.term);

    // Build the description content block.
    let mut desc = escaped_def;

    if !term.see_also.is_empty() {
        desc.push_str(&format_see_also(&term.see_also));
    }

    if term.children.is_empty() {
        output.push_str(&format!(
            "{prefix}terms.item([{} <{label}>], [{desc}]),\n",
            escape_typst(&term.term)
        ));
    } else {
        // Children become a nested #terms() inside the description.
        let mut child_terms: Vec<&crate::curate::terms::CuratedTerm> = term
            .children
            .iter()
            .filter_map(|name| terms_map.get(name.as_str()).copied())
            .collect();
        child_terms.sort_by(|a, b| a.term.to_lowercase().cmp(&b.term.to_lowercase()));

        output.push_str(&format!(
            "{prefix}terms.item([{} <{label}>], [{desc}\n",
            escape_typst(&term.term)
        ));
        let child_prefix = "  ".repeat(indent + 1);
        output.push_str(&format!("{child_prefix}#terms(tight: true,\n"));
        for child in child_terms {
            emit_term(child, terms_map, indent + 2, output);
        }
        output.push_str(&format!("{child_prefix})\n"));
        output.push_str(&format!("{prefix}]),\n"));
    }
}

// ── AST-aware prose search ──────────────────────────────────────────

/// Collect byte ranges of prose text in a Typst source.
///
/// Walks the AST using the same skip rules as the extractor (headings,
/// code, math, labels, refs, links, function calls) and returns sorted
/// byte ranges of `Text` and `Space` nodes — the only positions where
/// index markers can safely be inserted.
pub(crate) fn collect_prose_ranges(source: &str) -> Vec<(usize, usize)> {
    let root = parse(source);
    let mut ranges = Vec::new();
    walk_for_ranges(&root, 0, &mut ranges, false);
    // Merge adjacent ranges so multi-word terms spanning text+space+text match.
    merge_ranges(&mut ranges);
    ranges
}

fn walk_for_ranges(
    node: &SyntaxNode,
    base_offset: usize,
    ranges: &mut Vec<(usize, usize)>,
    in_heading: bool,
) {
    // Skip entirely — same nodes the extractor skips.
    if matches!(
        node.kind(),
        SyntaxKind::Raw
            | SyntaxKind::Equation
            | SyntaxKind::Label
            | SyntaxKind::Ref
            | SyntaxKind::RefMarker
            | SyntaxKind::Link
            | SyntaxKind::LineComment
            | SyntaxKind::BlockComment
            | SyntaxKind::Hash
    ) {
        return;
    }

    if node.kind() == SyntaxKind::Heading {
        let mut child_offset = base_offset;
        for child in node.children() {
            walk_for_ranges(child, child_offset, ranges, true);
            child_offset += child.len();
        }
        return;
    }

    match node.kind() {
        SyntaxKind::Text | SyntaxKind::Space if !in_heading => {
            let len = node.len();
            if len > 0 {
                ranges.push((base_offset, base_offset + len));
            }
        }
        _ => {
            let mut child_offset = base_offset;
            for child in node.children() {
                walk_for_ranges(child, child_offset, ranges, in_heading);
                child_offset += child.len();
            }
        }
    }
}

/// Merge adjacent/overlapping ranges into contiguous spans.
fn merge_ranges(ranges: &mut Vec<(usize, usize)>) {
    if ranges.len() <= 1 {
        return;
    }
    ranges.sort_by_key(|r| r.0);
    let mut write = 0;
    for read in 1..ranges.len() {
        if ranges[read].0 <= ranges[write].1 {
            ranges[write].1 = ranges[write].1.max(ranges[read].1);
        } else {
            write += 1;
            ranges[write] = ranges[read];
        }
    }
    ranges.truncate(write + 1);
}

/// Find a term in Typst source, only matching within prose text.
///
/// Parses the AST to determine safe byte ranges, then searches
/// the original source — skipping matches inside labels, links,
/// function arguments, code, math, and headings.
pub(crate) fn find_term_offset_in_prose(
    source: &str,
    term: &str,
    prose_ranges: &[(usize, usize)],
) -> Option<usize> {
    let lower_source = source.to_lowercase();
    let lower_term = term.to_lowercase();

    let mut start = 0;
    while let Some(pos) = lower_source[start..].find(&lower_term) {
        let abs_pos = start + pos;
        let abs_end = abs_pos + lower_term.len();

        // Check if match falls entirely within a merged prose range.
        let in_prose = prose_ranges
            .iter()
            .any(|&(rs, re)| abs_pos >= rs && abs_end <= re);

        if in_prose {
            // Skip if next char is '.' followed by alpha — inserting a marker
            // here would create a Typst field access on the marker's return value.
            // e.g., "plugins.gradle.org" → "plugins#index[plugins].gradle.org" is broken.
            let next_is_field_access = source.as_bytes().get(abs_end) == Some(&b'.')
                && source
                    .as_bytes()
                    .get(abs_end + 1)
                    .is_some_and(|b| b.is_ascii_alphabetic());
            if !next_is_field_access {
                return Some(abs_end);
            }
        }
        start = abs_pos + 1;
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn marker_top_level() {
        let r = TypstRenderer;
        assert_eq!(r.format_marker("OAuth", &[], false), "#index[OAuth]");
    }

    #[test]
    fn marker_top_level_main() {
        let r = TypstRenderer;
        assert_eq!(r.format_marker("OAuth", &[], true), "#index-main[OAuth]");
    }

    #[test]
    fn marker_child() {
        let r = TypstRenderer;
        assert_eq!(
            r.format_marker("OAuth", &["authentication".to_string()], false),
            r#"#index("authentication", "OAuth")"#
        );
    }

    #[test]
    fn marker_child_main() {
        let r = TypstRenderer;
        assert_eq!(
            r.format_marker("OAuth", &["authentication".to_string()], true),
            r#"#index-main("authentication", "OAuth")"#
        );
    }

    #[test]
    fn marker_grandchild() {
        let r = TypstRenderer;
        assert_eq!(
            r.format_marker(
                "OAuth",
                &["security".to_string(), "authentication".to_string()],
                false
            ),
            r#"#index("security", "authentication", "OAuth")"#
        );
    }

    use crate::render::Annotation;

    #[test]
    fn annotate_single_marker() {
        let r = TypstRenderer;
        let source = "OAuth provides delegated authorization.";
        let annotations = vec![Annotation {
            term: "OAuth".to_string(),
            parent_chain: Vec::new(),
            main: false,
            byte_offset: 5,
        }];
        let result = r.annotate(source, &annotations);
        assert!(result.contains("OAuth#index[OAuth] provides delegated authorization."));
        assert!(result.starts_with("#import"));
    }

    #[test]
    fn annotate_multiple_markers_descending() {
        let r = TypstRenderer;
        let source = "OAuth uses TLS for security.";
        let mut annotations = vec![
            Annotation {
                term: "TLS".to_string(),
                parent_chain: Vec::new(),
                main: false,
                byte_offset: 14, // after "TLS"
            },
            Annotation {
                term: "OAuth".to_string(),
                parent_chain: Vec::new(),
                main: true,
                byte_offset: 5, // after "OAuth"
            },
        ];
        annotations.sort_by(|a, b| b.byte_offset.cmp(&a.byte_offset));
        let result = r.annotate(source, &annotations);
        assert!(result.contains("OAuth#index-main[OAuth] uses TLS#index[TLS] for security."));
        assert!(result.starts_with("#import"));
    }

    #[test]
    fn annotate_with_parent_chain() {
        let r = TypstRenderer;
        let source = "OAuth is important.";
        let annotations = vec![Annotation {
            term: "OAuth".to_string(),
            parent_chain: vec!["authentication".to_string()],
            main: false,
            byte_offset: 5,
        }];
        let result = r.annotate(source, &annotations);
        assert!(result.contains(r#"#index("authentication", "OAuth")"#));
        assert!(result.starts_with("#import"));
    }

    #[test]
    fn annotate_prepends_import() {
        let r = TypstRenderer;
        let source = "OAuth is important.";
        let annotations = vec![Annotation {
            term: "OAuth".to_string(),
            parent_chain: Vec::new(),
            main: false,
            byte_offset: 5,
        }];
        let result = r.annotate(source, &annotations);
        assert!(result.starts_with("#import \"@preview/in-dexter:"));
    }

    #[test]
    fn annotate_skips_import_if_present() {
        let r = TypstRenderer;
        let source = "#import \"@preview/in-dexter:0.7.2\": *\n\nOAuth is important.";
        let annotations = vec![Annotation {
            term: "OAuth".to_string(),
            parent_chain: Vec::new(),
            main: false,
            byte_offset: source.find("OAuth").unwrap() + 5,
        }];
        let result = r.annotate(source, &annotations);
        assert_eq!(result.matches("in-dexter").count(), 1);
    }

    #[test]
    fn annotate_empty_annotations() {
        let r = TypstRenderer;
        let source = "No terms here.";
        let result = r.annotate(source, &[]);
        assert_eq!(result, source);
    }

    use crate::curate::terms::{CuratedTerm, CuratedTermsFile};

    fn sample_terms() -> CuratedTermsFile {
        CuratedTermsFile {
            version: 1,
            generated: "2026-03-20T00:00:00Z".to_string(),
            source_dir: "docs/".to_string(),
            document_count: 3,
            terms: vec![
                CuratedTerm {
                    term: "API key".to_string(),
                    definition: "A credential for authenticating API requests.".to_string(),
                    parent: None,
                    aliases: Vec::new(),
                    see_also: Vec::new(),
                    children: Vec::new(),
                    locations: Vec::new(),
                },
                CuratedTerm {
                    term: "authentication".to_string(),
                    definition: "The process of verifying identity.".to_string(),
                    parent: None,
                    aliases: Vec::new(),
                    see_also: Vec::new(),
                    children: vec!["OAuth".to_string()],
                    locations: Vec::new(),
                },
                CuratedTerm {
                    term: "OAuth".to_string(),
                    definition: "An open standard for token-based authorization.".to_string(),
                    parent: Some("authentication".to_string()),
                    aliases: vec!["OAuth 2.0".to_string()],
                    see_also: vec!["API key".to_string()],
                    children: Vec::new(),
                    locations: Vec::new(),
                },
                CuratedTerm {
                    term: "TLS".to_string(),
                    definition: "Transport Layer Security protocol.".to_string(),
                    parent: None,
                    aliases: Vec::new(),
                    see_also: Vec::new(),
                    children: Vec::new(),
                    locations: Vec::new(),
                },
            ],
        }
    }

    #[test]
    fn glossary_contains_all_terms() {
        let r = TypstRenderer;
        let g = r.glossary(&sample_terms(), None);
        assert!(
            g.contains("[API key <term-api-key>]"),
            "should contain API key with label"
        );
        assert!(
            g.contains("[authentication <term-authentication>]"),
            "should contain authentication with label"
        );
        assert!(
            g.contains("[OAuth <term-oauth>]"),
            "should contain OAuth with label"
        );
        assert!(
            g.contains("[TLS <term-tls>]"),
            "should contain TLS with label"
        );
    }

    #[test]
    fn glossary_uses_code_mode() {
        let r = TypstRenderer;
        let g = r.glossary(&sample_terms(), None);
        assert!(
            g.contains("#terms(tight: false,"),
            "should use code-mode #terms()"
        );
        assert!(g.contains("terms.item("), "should use terms.item() calls");
    }

    #[test]
    fn glossary_children_nested() {
        let r = TypstRenderer;
        let g = r.glossary(&sample_terms(), None);
        // OAuth is a child of authentication — should be in a nested #terms()
        assert!(
            g.contains("#terms(tight: true,\n"),
            "should have nested #terms for children"
        );
    }

    #[test]
    fn glossary_see_also_linked() {
        let r = TypstRenderer;
        let g = r.glossary(&sample_terms(), None);
        assert!(
            g.contains("#link(<term-api-key>)[API key]"),
            "see_also should be a link to the term label"
        );
    }

    #[test]
    fn glossary_has_header_comment() {
        let r = TypstRenderer;
        let g = r.glossary(&sample_terms(), None);
        assert!(g.starts_with("// Generated by colophon"));
    }

    #[test]
    fn glossary_alphabetical_order() {
        let r = TypstRenderer;
        let g = r.glossary(&sample_terms(), None);
        let api_pos = g.find("<term-api-key>").unwrap();
        let auth_pos = g.find("<term-authentication>").unwrap();
        let tls_pos = g.find("<term-tls>").unwrap();
        assert!(api_pos < auth_pos, "API key before authentication");
        assert!(auth_pos < tls_pos, "authentication before TLS");
    }

    #[test]
    fn glossary_with_spacing() {
        let r = TypstRenderer;
        let g = r.glossary(&sample_terms(), Some("12pt"));
        assert!(
            g.contains("#terms(tight: false, spacing: 12pt,"),
            "should include spacing param"
        );
    }

    #[test]
    fn glossary_empty_terms() {
        let r = TypstRenderer;
        let terms = CuratedTermsFile {
            version: 1,
            generated: "2026-03-20T00:00:00Z".to_string(),
            source_dir: ".".to_string(),
            document_count: 0,
            terms: Vec::new(),
        };
        let g = r.glossary(&terms, None);
        assert!(g.contains("// Generated by colophon"));
        assert!(!g.contains("terms.item("));
    }

    // ── Prose range and AST-aware search tests ──

    #[test]
    fn prose_ranges_skip_labels() {
        let source = "= Intro <intro>\n\nSome text about channels.";
        let ranges = collect_prose_ranges(source);
        // "channels" in prose should be in ranges
        let ch_pos = source.find("channels").unwrap();
        assert!(ranges.iter().any(|&(s, e)| ch_pos >= s && ch_pos + 8 <= e));
        // "<intro>" label should NOT be in ranges
        let label_pos = source.find("<intro>").unwrap();
        assert!(!ranges
            .iter()
            .any(|&(s, e)| label_pos >= s && label_pos + 7 <= e));
    }

    #[test]
    fn prose_ranges_skip_link_targets() {
        let source = r#"See #link(<channels>)[Channels] for details."#;
        let ranges = collect_prose_ranges(source);
        // The label "<channels>" inside #link() should not be in ranges.
        // The #link call starts with Hash which is skipped entirely.
        let label_pos = source.find("<channels>").unwrap();
        assert!(
            !ranges
                .iter()
                .any(|&(s, e)| label_pos >= s && label_pos + 10 <= e),
            "label inside #link should be excluded from prose ranges"
        );
    }

    #[test]
    fn find_in_prose_skips_link_label() {
        let source = r#"See #link(<channels>)[Channels] for details about channels."#;
        let ranges = collect_prose_ranges(source);
        let offset = find_term_offset_in_prose(source, "channels", &ranges);
        assert!(offset.is_some(), "should find 'channels' in prose");
        // Should NOT match inside <channels> label
        let found_pos = offset.unwrap() - 8; // offset is AFTER the term
        let label_pos = source.find("<channels>").unwrap() + 1; // skip the <
        assert_ne!(found_pos, label_pos, "should not match inside label");
        // May match "Channels" in the [Channels] display text (valid prose)
        // or "channels" in the trailing prose — both are correct.
    }

    #[test]
    fn find_in_prose_skips_code() {
        let source = "Use `OAuth` for auth. OAuth is the standard.";
        let ranges = collect_prose_ranges(source);
        let offset = find_term_offset_in_prose(source, "OAuth", &ranges);
        assert!(offset.is_some());
        // Should match the prose occurrence, not inside backticks
        let found_pos = offset.unwrap() - 5;
        let code_pos = source.find("`OAuth`").unwrap() + 1;
        assert_ne!(found_pos, code_pos, "should not match inside code");
    }

    #[test]
    fn find_in_prose_multiword_across_nodes() {
        let source = "Use API key for access.";
        let ranges = collect_prose_ranges(source);
        let offset = find_term_offset_in_prose(source, "API key", &ranges);
        assert!(
            offset.is_some(),
            "multi-word term should match across text+space nodes"
        );
    }

    #[test]
    fn find_in_prose_skips_field_access_position() {
        // "plugins.gradle.org" — inserting after "plugins" would create
        // #index[plugins].gradle which Typst reads as field access.
        let source = "Visit plugins.gradle.org for plugins and extensions.";
        let ranges = collect_prose_ranges(source);
        let offset = find_term_offset_in_prose(source, "plugins", &ranges);
        assert!(offset.is_some(), "should find 'plugins' in safe position");
        let found_pos = offset.unwrap() - 7;
        // Should match the second "plugins" (not followed by '.g')
        let safe_pos = source.rfind("plugins").unwrap();
        assert_eq!(found_pos, safe_pos, "should match the safe occurrence");
    }

    #[test]
    fn find_in_prose_field_access_only_occurrence_skipped() {
        // If the only occurrence is followed by '.alpha', skip it entirely.
        let source = "Visit plugins.gradle.org for details.";
        let ranges = collect_prose_ranges(source);
        let offset = find_term_offset_in_prose(source, "plugins", &ranges);
        assert!(
            offset.is_none(),
            "should not match when only in dotted name"
        );
    }

    #[test]
    fn find_in_prose_not_found_only_in_syntax() {
        let source = r#"#set text(font: "channels")"#;
        let ranges = collect_prose_ranges(source);
        let offset = find_term_offset_in_prose(source, "channels", &ranges);
        assert!(
            offset.is_none(),
            "term only in function call should not match"
        );
    }
}
