//! Typst renderer — in-dexter index markers and term list glossary.

use crate::curate::terms::CuratedTermsFile;
use crate::render::{Annotation, Renderer};

/// In-dexter import line prepended to annotated files.
const IN_DEXTER_IMPORT: &str = "#import \"@preview/in-dexter:0.7.2\": *\n";

/// Typst renderer using in-dexter index markers.
pub struct TypstRenderer;

impl TypstRenderer {
    /// Format a single index marker call.
    pub fn format_marker(&self, term: &str, parent_chain: &[String], main: bool) -> String {
        let func = if main { "#index-main" } else { "#index" };
        if parent_chain.is_empty() {
            format!("{func}[{term}]")
        } else {
            let args: Vec<String> = parent_chain
                .iter()
                .map(|p| format!("\"{p}\""))
                .chain(std::iter::once(format!("\"{term}\"")))
                .collect();
            format!("{func}({})", args.join(", "))
        }
    }
}

impl Renderer for TypstRenderer {
    fn annotate(&self, source: &str, annotations: &[Annotation]) -> String {
        if annotations.is_empty() {
            return source.to_string();
        }

        let mut result = source.to_string();

        // Insert markers at descending byte offsets.
        for ann in annotations {
            let marker = self.format_marker(&ann.term, &ann.parent_chain, ann.main);
            if ann.byte_offset <= result.len() {
                result.insert_str(ann.byte_offset, &marker);
            }
        }

        // Prepend import if not already present.
        if !result.contains("in-dexter") {
            result.insert_str(0, IN_DEXTER_IMPORT);
        }

        result
    }

    fn glossary(&self, terms: &CuratedTermsFile, spacing: Option<&str>) -> String {
        use std::collections::HashMap;

        let mut output = String::from("// Generated by colophon\n\n");

        if terms.terms.is_empty() {
            return output;
        }

        // Build a lookup map: term name -> CuratedTerm
        let terms_map: HashMap<&str, &crate::curate::terms::CuratedTerm> =
            terms.terms.iter().map(|t| (t.term.as_str(), t)).collect();

        // Collect top-level terms (no parent)
        let mut top_level: Vec<&crate::curate::terms::CuratedTerm> =
            terms.terms.iter().filter(|t| t.parent.is_none()).collect();
        top_level.sort_by(|a, b| a.term.to_lowercase().cmp(&b.term.to_lowercase()));

        // Emit in code mode via #terms() for spacing control.
        let spacing_arg = spacing
            .map(|s| format!(", spacing: {s}"))
            .unwrap_or_default();
        output.push_str(&format!("#terms(tight: false{spacing_arg},\n"));

        for term in top_level {
            emit_term(term, &terms_map, 1, &mut output);
        }

        output.push_str(")\n");
        output
    }
}

/// Escape Typst-significant characters in prose text.
///
/// Prevents `@mentions` becoming references, `#func` becoming code-mode
/// entries, `<label>` becoming labels, and `$math$` becoming equations.
fn escape_typst(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for ch in text.chars() {
        match ch {
            '@' | '#' | '<' | '$' | '_' | '*' => {
                out.push('\\');
                out.push(ch);
            }
            _ => out.push(ch),
        }
    }
    out
}

/// Convert a term name to a Typst label: lowercase, non-alphanumeric → hyphens, deduplicated.
fn term_label(name: &str) -> String {
    let mut label = String::with_capacity(name.len() + 5);
    label.push_str("term-");
    let mut prev_hyphen = false;
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            label.push(ch.to_ascii_lowercase());
            prev_hyphen = false;
        } else if !prev_hyphen {
            label.push('-');
            prev_hyphen = true;
        }
    }
    // Trim trailing hyphen.
    if label.ends_with('-') {
        label.pop();
    }
    label
}

/// Format see_also entries as Typst links to glossary term labels.
fn format_see_also(see_also: &[String]) -> String {
    let links: Vec<String> = see_also
        .iter()
        .map(|name| format!("#link(<{}>)[{}]", term_label(name), escape_typst(name)))
        .collect();
    format!(" _See also: {}_", links.join(", "))
}

/// Recursively emit a term as a `terms.item()` call in Typst code mode.
fn emit_term(
    term: &crate::curate::terms::CuratedTerm,
    terms_map: &std::collections::HashMap<&str, &crate::curate::terms::CuratedTerm>,
    indent: usize,
    output: &mut String,
) {
    let prefix = "  ".repeat(indent);
    let escaped_def = escape_typst(&term.definition);
    let label = term_label(&term.term);

    // Build the description content block.
    let mut desc = escaped_def;

    if !term.see_also.is_empty() {
        desc.push_str(&format_see_also(&term.see_also));
    }

    if term.children.is_empty() {
        output.push_str(&format!(
            "{prefix}terms.item([{} <{label}>], [{desc}]),\n",
            escape_typst(&term.term)
        ));
    } else {
        // Children become a nested #terms() inside the description.
        let mut child_terms: Vec<&crate::curate::terms::CuratedTerm> = term
            .children
            .iter()
            .filter_map(|name| terms_map.get(name.as_str()).copied())
            .collect();
        child_terms.sort_by(|a, b| a.term.to_lowercase().cmp(&b.term.to_lowercase()));

        output.push_str(&format!(
            "{prefix}terms.item([{} <{label}>], [{desc}\n",
            escape_typst(&term.term)
        ));
        let child_prefix = "  ".repeat(indent + 1);
        output.push_str(&format!("{child_prefix}#terms(tight: true,\n"));
        for child in child_terms {
            emit_term(child, terms_map, indent + 2, output);
        }
        output.push_str(&format!("{child_prefix})\n"));
        output.push_str(&format!("{prefix}]),\n"));
    }
}

// Re-export for render/mod.rs convenience.
pub(crate) use crate::typst_prose::{collect_prose_ranges, find_term_offset_in_prose};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn marker_top_level() {
        let r = TypstRenderer;
        assert_eq!(r.format_marker("OAuth", &[], false), "#index[OAuth]");
    }

    #[test]
    fn marker_top_level_main() {
        let r = TypstRenderer;
        assert_eq!(r.format_marker("OAuth", &[], true), "#index-main[OAuth]");
    }

    #[test]
    fn marker_child() {
        let r = TypstRenderer;
        assert_eq!(
            r.format_marker("OAuth", &["authentication".to_string()], false),
            r#"#index("authentication", "OAuth")"#
        );
    }

    #[test]
    fn marker_child_main() {
        let r = TypstRenderer;
        assert_eq!(
            r.format_marker("OAuth", &["authentication".to_string()], true),
            r#"#index-main("authentication", "OAuth")"#
        );
    }

    #[test]
    fn marker_grandchild() {
        let r = TypstRenderer;
        assert_eq!(
            r.format_marker(
                "OAuth",
                &["security".to_string(), "authentication".to_string()],
                false
            ),
            r#"#index("security", "authentication", "OAuth")"#
        );
    }

    use crate::render::Annotation;

    #[test]
    fn annotate_single_marker() {
        let r = TypstRenderer;
        let source = "OAuth provides delegated authorization.";
        let annotations = vec![Annotation {
            term: "OAuth".to_string(),
            parent_chain: Vec::new(),
            main: false,
            byte_offset: 5,
        }];
        let result = r.annotate(source, &annotations);
        assert!(result.contains("OAuth#index[OAuth] provides delegated authorization."));
        assert!(result.starts_with("#import"));
    }

    #[test]
    fn annotate_multiple_markers_descending() {
        let r = TypstRenderer;
        let source = "OAuth uses TLS for security.";
        let mut annotations = vec![
            Annotation {
                term: "TLS".to_string(),
                parent_chain: Vec::new(),
                main: false,
                byte_offset: 14, // after "TLS"
            },
            Annotation {
                term: "OAuth".to_string(),
                parent_chain: Vec::new(),
                main: true,
                byte_offset: 5, // after "OAuth"
            },
        ];
        annotations.sort_by(|a, b| b.byte_offset.cmp(&a.byte_offset));
        let result = r.annotate(source, &annotations);
        assert!(result.contains("OAuth#index-main[OAuth] uses TLS#index[TLS] for security."));
        assert!(result.starts_with("#import"));
    }

    #[test]
    fn annotate_with_parent_chain() {
        let r = TypstRenderer;
        let source = "OAuth is important.";
        let annotations = vec![Annotation {
            term: "OAuth".to_string(),
            parent_chain: vec!["authentication".to_string()],
            main: false,
            byte_offset: 5,
        }];
        let result = r.annotate(source, &annotations);
        assert!(result.contains(r#"#index("authentication", "OAuth")"#));
        assert!(result.starts_with("#import"));
    }

    #[test]
    fn annotate_prepends_import() {
        let r = TypstRenderer;
        let source = "OAuth is important.";
        let annotations = vec![Annotation {
            term: "OAuth".to_string(),
            parent_chain: Vec::new(),
            main: false,
            byte_offset: 5,
        }];
        let result = r.annotate(source, &annotations);
        assert!(result.starts_with("#import \"@preview/in-dexter:"));
    }

    #[test]
    fn annotate_skips_import_if_present() {
        let r = TypstRenderer;
        let source = "#import \"@preview/in-dexter:0.7.2\": *\n\nOAuth is important.";
        let annotations = vec![Annotation {
            term: "OAuth".to_string(),
            parent_chain: Vec::new(),
            main: false,
            byte_offset: source.find("OAuth").unwrap() + 5,
        }];
        let result = r.annotate(source, &annotations);
        assert_eq!(result.matches("in-dexter").count(), 1);
    }

    #[test]
    fn annotate_empty_annotations() {
        let r = TypstRenderer;
        let source = "No terms here.";
        let result = r.annotate(source, &[]);
        assert_eq!(result, source);
    }

    use crate::curate::terms::{CuratedTerm, CuratedTermsFile};

    fn sample_terms() -> CuratedTermsFile {
        CuratedTermsFile {
            version: 1,
            generated: "2026-03-20T00:00:00Z".to_string(),
            source_dir: "docs/".to_string(),
            document_count: 3,
            terms: vec![
                CuratedTerm {
                    term: "API key".to_string(),
                    definition: "A credential for authenticating API requests.".to_string(),
                    parent: None,
                    aliases: Vec::new(),
                    see_also: Vec::new(),
                    children: Vec::new(),
                    locations: Vec::new(),
                },
                CuratedTerm {
                    term: "authentication".to_string(),
                    definition: "The process of verifying identity.".to_string(),
                    parent: None,
                    aliases: Vec::new(),
                    see_also: Vec::new(),
                    children: vec!["OAuth".to_string()],
                    locations: Vec::new(),
                },
                CuratedTerm {
                    term: "OAuth".to_string(),
                    definition: "An open standard for token-based authorization.".to_string(),
                    parent: Some("authentication".to_string()),
                    aliases: vec!["OAuth 2.0".to_string()],
                    see_also: vec!["API key".to_string()],
                    children: Vec::new(),
                    locations: Vec::new(),
                },
                CuratedTerm {
                    term: "TLS".to_string(),
                    definition: "Transport Layer Security protocol.".to_string(),
                    parent: None,
                    aliases: Vec::new(),
                    see_also: Vec::new(),
                    children: Vec::new(),
                    locations: Vec::new(),
                },
            ],
        }
    }

    #[test]
    fn glossary_contains_all_terms() {
        let r = TypstRenderer;
        let g = r.glossary(&sample_terms(), None);
        assert!(
            g.contains("[API key <term-api-key>]"),
            "should contain API key with label"
        );
        assert!(
            g.contains("[authentication <term-authentication>]"),
            "should contain authentication with label"
        );
        assert!(
            g.contains("[OAuth <term-oauth>]"),
            "should contain OAuth with label"
        );
        assert!(
            g.contains("[TLS <term-tls>]"),
            "should contain TLS with label"
        );
    }

    #[test]
    fn glossary_uses_code_mode() {
        let r = TypstRenderer;
        let g = r.glossary(&sample_terms(), None);
        assert!(
            g.contains("#terms(tight: false,"),
            "should use code-mode #terms()"
        );
        assert!(g.contains("terms.item("), "should use terms.item() calls");
    }

    #[test]
    fn glossary_children_nested() {
        let r = TypstRenderer;
        let g = r.glossary(&sample_terms(), None);
        // OAuth is a child of authentication — should be in a nested #terms()
        assert!(
            g.contains("#terms(tight: true,\n"),
            "should have nested #terms for children"
        );
    }

    #[test]
    fn glossary_see_also_linked() {
        let r = TypstRenderer;
        let g = r.glossary(&sample_terms(), None);
        assert!(
            g.contains("#link(<term-api-key>)[API key]"),
            "see_also should be a link to the term label"
        );
    }

    #[test]
    fn glossary_has_header_comment() {
        let r = TypstRenderer;
        let g = r.glossary(&sample_terms(), None);
        assert!(g.starts_with("// Generated by colophon"));
    }

    #[test]
    fn glossary_alphabetical_order() {
        let r = TypstRenderer;
        let g = r.glossary(&sample_terms(), None);
        let api_pos = g.find("<term-api-key>").unwrap();
        let auth_pos = g.find("<term-authentication>").unwrap();
        let tls_pos = g.find("<term-tls>").unwrap();
        assert!(api_pos < auth_pos, "API key before authentication");
        assert!(auth_pos < tls_pos, "authentication before TLS");
    }

    #[test]
    fn glossary_with_spacing() {
        let r = TypstRenderer;
        let g = r.glossary(&sample_terms(), Some("12pt"));
        assert!(
            g.contains("#terms(tight: false, spacing: 12pt,"),
            "should include spacing param"
        );
    }

    #[test]
    fn glossary_empty_terms() {
        let r = TypstRenderer;
        let terms = CuratedTermsFile {
            version: 1,
            generated: "2026-03-20T00:00:00Z".to_string(),
            source_dir: ".".to_string(),
            document_count: 0,
            terms: Vec::new(),
        };
        let g = r.glossary(&terms, None);
        assert!(g.contains("// Generated by colophon"));
        assert!(!g.contains("terms.item("));
    }
}
